function options = parameters(data_name)
    if(strcmp(data_name,'madelon'))
        options=struct('KernelParam',1, ...
            'NN',8,...
            'tol',1e-10, ...
            'T',100, ...
            'lambda_A', 1,...
            'lambda_I', 0.05,...
            'lambda', 0.5,...
            'performance', 0);
    elseif(strcmp(data_name,'space_ga'))
        options=struct('KernelParam',1, ...
            'NN',8,...
            'tol',1e-10, ...
            'T',100, ...
            'lambda_A', 0.0005,...
            'lambda_I', 0.05,...
            'lambda', 0.01,...
            'performance', 0);
    elseif(strcmp(data_name,'abalone'))
        options=struct('KernelParam',1, ...
            'NN',8,...
            'tol',1e-10, ...
            'T',100, ...
            'lambda_A', 0.001,...
            'lambda_I', 0.001,...
            'lambda', 0.001,...
            'performance', 0);
    elseif(strcmp(data_name,'mushrooms'))
        options = struct('KernelParam',4, ...
                 'NN',8,...
                 'tol',1e-6, ...
                 'T',30, ...
                 'lambda_A', 0.0005,... 
                 'lambda_I', 0.0005,...
                 'lambda', 0.0005,...
                 'performance', 0); 
    elseif(strcmp(data_name,'phishing'))
        options=struct('KernelParam',1, ...
            'NN',8,...
            'tol',1e-6, ...
            'T',100, ...
            'lambda_A', 0.001,...
            'lambda_I', 0.0005,...
            'lambda', 0.0005,...
            'performance', 0);
    elseif(strcmp(data_name,'a8a'))
        options=struct('KernelParam',3, ...
            'NN',8,...
            'tol',1e-10, ...
            'T',100, ...
            'lambda_A', 1,...
            'lambda_I', 0.05,...
            'lambda', 0.1,...
            'performance', 0);
    elseif(strcmp(data_name,'w7a'))
        options=struct('KernelParam',10, ...
            'NN',8,...
            'tol',1e-6, ...
            'T',100, ...
            'lambda_A', 0.01,...
            'lambda_I', 0.005,...
            'lambda', 0.01,...
            'performance', 0);
    elseif(strcmp(data_name,'a9a'))
        options=struct('KernelParam',3, ...
            'NN',8,...
            'tol',1e-10, ...
            'T',100, ...
            'lambda_A', 1,...
            'lambda_I', 0.05,...
            'lambda', 0.1,...
            'performance', 0);
    elseif(strcmp(data_name,'cod-rna'))
        options=struct('KernelParam',0.1, ...
            'NN',8,...
            'tol',1e-10, ...
            'T',100, ...
            'lambda_A', 0.001,...
            'lambda_I', 0.1,...
            'lambda', 0.001,...
            'performance', 0);
    elseif(strcmp(data_name,'connect-4'))
        options=struct('KernelParam',3, ...
            'NN',8,...
            'tol',1e-10, ...
            'T',100, ...
            'lambda_A', 0.1,...
            'lambda_I', 0.1,...
            'lambda', 0.1,...
            'performance', 0);
    elseif(strcmp(data_name,'ijcnn1'))
        options=struct('KernelParam',2, ...
            'NN',8,...
            'tol',1e-10, ...
            'T',100, ...
            'lambda_A', 0.01,...
            'lambda_I', 0.01,...
            'lambda', 0.01,...
            'performance', 0);
    elseif(strcmp(data_name,'skin_nonskin'))
        options=struct('KernelParam',256, ...
            'NN',8,...
            'tol',1e-10, ...
            'T',100, ...
            'lambda_A', 0.001,...
            'lambda_I', 0.001,...
            'lambda', 1,...
            'performance', 0);
   elseif(strcmp(data_name,'YearPredictionMSD'))
        options=struct('KernelParam',0.1, ...
            'NN',8,...
            'tol',1e-10, ...
            'T',100, ...
            'lambda_A', 0.0005,...
            'lambda_I', 0.0005,...
            'lambda', 0.001,...
            'performance', 0);
    end
end